### ISSUE TITLE
Improve navigation (hotkeys and tabindex)

### ISSUE THREAD

**Issue by roxane42** [Comprendre-Steem/fast-reply#4]
At the moment, using the apps requires a lot of mouse mouvements and clicks.
This could be greatly improved by adding `tabindex` to switch from one field/button to the other selected order.

Additionally, adding hotkeys would make the process even smoother.

The goal here is to be able to use the app without a mouse even if it means having to memorize a few keys combinations.

**Comment by oroger** [comment]
Tab indexes will not be used as this might cause issue with other tools such a impaired sight, ...

But hotkeys have been added for the followings actions:

| Hotkey             | Action                   |
| ------------------ | ------------------------ |
| ALT + ESC          | Focus on reply textarea  |
| ALT + F1-F12         | Emojis                   |
| CTRL + F9          | Reply                    |
| CTRL + F10         | Reply and Vote           |
| CTRL + F11         | Vote                     |
| CTRL + F12         | Ignore                   |
| CTRL + HOME        | Previous comment         |
| CTRL + END         | Next comment             |
| ALT + HOME         | Previous quickvote value |
| ALT + END          | Next quickvote value     |
| ALT + SHIFT + HOME | Vote - 10%               |
| ALT + SHIFT + END  | Vote + 10%               |
